### ISSUE TITLE
stateful URL?

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#10]
One of the useful features of the old bscit site was allowing the query to be exposed in the URL so links could be sent and embedded in external pages. Implement some similar solution?

**Comment by jdeck88** [comment]
If you search for Annie Alexander between years 1910 and 1920 that is already a static URL like:

http://ecoreader.berkeley.edu/rest/volumes/Alexander,%20Annie%20Montague?begin_date=1920&end_date=1930&section_title=&volume_id=

which will give you a JSON response. 

So, i imagine that you don't actually want to look at the JSON, but want to see HTML.  

I'm also assuming that you just want to see the results and not statically link to images.  

If this is all true, then i think i just need to pop in some Javascript that parses an incoming URL sends the AJAX request automatically with the incoming URL like:

http://ecoreader.berkeley.edu/?author=Alexander,%20Annie%20Montague&begin_date=1920&end_date=1930&section_title=&volume_id=

Is it necessary to coordinate this with already saved queries from the old field notebook site?  that could be tricky.

John

**Comment by mkoo** [comment]
Not necessary to coordinate with the old site (although that means more work for Archives team to update on OAC etc so perhaps I am speaking out of turn here!). However I'm not seeing the static URL when I am getting search results or cruising through pages.

I only see ecoreader.berkeley.edu/#
So updateQueryString (something something...)?

**Comment by jdeck88** [comment]
I was thinking a "Share" Link so users can copy the correct URL.
The parameters are not instantly reflected in the URL since the javascript
is calling the various services directly and doing the rendering.  This is
different than the old perl site which had the server rendering everything.

John

On Tue, Oct 20, 2015 at 8:28 AM, Michelle Koo notifications@github.com
wrote:

> Not necessary to coordinate with the old site (although that means more
> work for Archives team to update on OAC etc so perhaps I am speaking out of
> turn here!). However I'm not seeing the static URL when I am getting search
> results or cruising through pages.
> 
> I only see ecoreader.berkeley.edu/#
> So updateQueryString (something something...)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BNHM/ecoreader/issues/10#issuecomment-149602412.

## 

John Deck
(541) 914-4739

**Comment by mkoo** [comment]
Share link is perfect solution

**Comment by jdeck88** [comment]
This is now added and working, e.g. see:

http://ecoreader.berkeley.edu/?authors=Alexander%2C%20Annie%20Montague&begin_date=1920&end_date=1928&scanned_only=true

**Comment by mkoo** [comment]
Awesome!
