### ISSUE TITLE
Volumes missing on some authors MODS?

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#14]
in ecoreader, see Kellogg, L. (no volume just year) vs. Beck, Rollo (v509 shows up). Sections are correction appearing with their headings.

**Comment by jdeck88** [comment]
can you clarify what you mean by "Sections are correction appearing with their headings"?  I think this issue should be labelled: "Standardize volume and section headings in MODS files".   Also, not quite sure its a bug but probably more "fix data".   

If we're talking about section headings I would ask for the author to appear in the section title.  Sometimes it appears there and sometimes it doesn't. We need to decide if we add the author somehow in MODS (structuring AT accordingly)  or i add them in code.

**Comment by cfidler** [comment]
Ahh, I see what you mean. With rare exception, the titles are from the old database. I can clean up the volume titles in AT and reimport them.

**Comment by mkoo** [comment]
Yeah you're right. need a new tag "Data issue"

**Comment by mkoo** [comment]
@cfidler: closing for now since you will reimport
