### ISSUE TITLE
M. Koford volumes missing

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#20]
The Mary Koford volumes aren't showing up. Koford, M. is not in the dropdown but I see I think I sent those MODS files a few weeks ago.

**Comment by jdeck88** [comment]
A couple of issues here... grouping was happening on family_name and there is another Koford in the authors list.  I changed this to grouping on family_name plus given name.  
I also changed the author list to lookup based on names in a section because that is how the searches happen).
