### ISSUE TITLE
Some volume identifiers don't conform to standard syntax

### ISSUE THREAD

**Issue by jdeck88** [BNHM/ecoreader#24]
Following volume identifiers are wrong:
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA_v635
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA_v636
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA_v637
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA_v638
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA_v639

They should actually be:
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA/v635
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA/v636
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA/v637
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA/v638
http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/BellDA/v639

**Comment by cfidler** [comment]
Submitted fixed records.
