### ISSUE TITLE
Invalid volume identifiers

### ISSUE THREAD

**Issue by jdeck88** [BNHM/ecoreader#27]
I wrote a check for volume_identifier because i noticed (last week) a few volume IDs that were not formatted like the others... All of the following volume_identifiers are misssing a "/" between the author name and the volume_id. They can all be fixed by inserting that "/".  Sorry for the long list, but just pasting them here.

validating all files in /Users/jdeck/IdeaProjects/ecoreader/ecoreader/docs/mvz
httpweb.corral.tacc.utexas.eduMVZfieldnotesCampCLv553-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CampCL_v553)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCampCLv554-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CampCL_v554)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCampCLv555-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CampCL_v555)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCampCLv556-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CampCL_v556)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCampCLv557-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CampCL_v557)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCaseSMv558-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CaseSM_v558)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCavalierCv559-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CavalierC_v559)
httpweb.corral.tacc.utexas.eduMVZfieldnotesChattinJEv560-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ChattinJE_v560)
httpweb.corral.tacc.utexas.eduMVZfieldnotesChattinJEv561-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ChattinJE_v561)
httpweb.corral.tacc.utexas.eduMVZfieldnotesChristmanGMv562-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ChristmanGM_v562)
httpweb.corral.tacc.utexas.eduMVZfieldnotesChristmanGMv563-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ChristmanGM_v563)
httpweb.corral.tacc.utexas.eduMVZfieldnotesClarkeFCv565-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ClarkeFC_v565)
httpweb.corral.tacc.utexas.eduMVZfieldnotesClarkeFCv566-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ClarkeFC_v566)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCogswellHLv567-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CogswellHL_v567)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCogswellHLv569-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CogswellHL_v569)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCogswellHLv570-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CogswellHL_v570)
httpweb.corral.tacc.utexas.eduMVZfieldnotesComptonLVv571-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ComptonLV_v571)
httpweb.corral.tacc.utexas.eduMVZfieldnotesComptonLVv573-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ComptonLV_v573)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCrowleyJv574-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CrowleyJ_v574)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCsutiBAv576-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CsutiBA_v576)
httpweb.corral.tacc.utexas.eduMVZfieldnotesCulbreathJv577-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/CulbreathJ_v577)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDalquestWWv564-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DalquestWW_v564)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDalquestWWv568-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DalquestWW_v568)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDalquestWWv572-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DalquestWW_v572)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDalquestWWv575-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DalquestWW_v575)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDardaDMv578-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DardaDM_v578)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDardaDMv641-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DardaDM_v641)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisJv585-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisJ_v585)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisJv589-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisJ_v589)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisJv642-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisJ_v642)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisJv644-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisJ_v644)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisJv645-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisJ_v645)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisWBv591-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisWB_v591)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisWBv646-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisWB_v646)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDavisWBv647-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DavisWB_v647)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDeBenedictisPAv579-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DeBenedictisPA_v579)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDeBenedictisPAv580-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DeBenedictisPA_v580)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDemayISv582-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DemayIS_v582)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv583-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v583)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv584-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v584)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv586-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v586)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv587-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v587)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv592-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v592)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv593-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v593)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv594-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v594)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv595-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v595)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv596-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v596)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv597-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v597)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv598-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v598)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonJSv599-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonJS_v599)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonKLv600-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonKL_v600)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDixonKLv601-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DixonKL_v601)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDunmireWWv648-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DunmireWW_v648)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDurhamFEv649-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DurhamFE_v649)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDurrantSDv650-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DurrantSD_v650)
httpweb.corral.tacc.utexas.eduMVZfieldnotesDziadoszVMv651-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DziadoszVM_v651)

**Comment by cfidler** [comment]
Fixes submitted

**Comment by jdeck88** [comment]
Two more!
httpweb.corral.tacc.utexas.eduMVZfieldnotesDziadoszVMv651-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/DziadoszVM_v651)
httpweb.corral.tacc.utexas.eduMVZfieldnotesComptonLVv573-mods.xml has an invalid Volume Identifier: (http://web.corral.tacc.utexas.edu/MVZ/fieldnotes/ComptonLV_v573)

John

**Comment by cfidler** [comment]
Done.
