### ISSUE TITLE
jump to page # function in Read mode

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#28]
In the previous bscit site, users could navigate and jump to a specific page by number (e.g., "page ____ of 120" where the user could fill in or change the number in the blank). Karen requested it and since then I've missed it too.

This missing feature is somewhat mitigated by the 'View Section' but you cannot 'jump to' a page number, just scroll. Also a user cannot go seamlessly from View section to Read section mode once the page is found. If the latter could be done then maybe this issue would be addressed.

**Comment by jdeck88** [comment]
After talking to folks here at Berkeley we decided to:
Integrate View Section and Read Section so its all View Section.
Click on image during View mode and have it zoom in.
Add the jump to page number as discussed in the original note.

**Comment by jdeck88** [comment]
This is now implemented.

**Comment by mkoo** [comment]
very nice!
