### ISSUE TITLE
link pages from View section to Read section mode

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#32]
Creating a separate issue from #28 where it was first mentioned.
In view section mode, add a link that allows user to go seamlessly from View section mode to Read section mode on a selected page. (yes, for the lazy)

**Comment by jdeck88** [comment]
This is now fixed.. view/read section modes merged.

**Comment by mkoo** [comment]
This might need a popup tip or other tool help as I did not see the zoom
tool appear except unexpectedly popping up when hovering on the image... it
was not consistent for an impatient user.

**Comment by jdeck88** [comment]
what about some explanatory text under the image?

On Mon, Feb 29, 2016 at 3:30 PM, Michelle Koo notifications@github.com
wrote:

> This might need a popup tip or other tool help as I did not see the zoom
> tool appear except unexpectedly popping up when hovering on the image... it
> was not consistent for an impatient user.
> 
> On Mon, Feb 29, 2016 at 7:04 AM, John Deck notifications@github.com
> wrote:
> 
> > Closed #32 https://github.com/BNHM/ecoreader/issues/32.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/BNHM/ecoreader/issues/32#event-571239320.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BNHM/ecoreader/issues/32#issuecomment-190449193.

## 

John Deck
(541) 914-4739

**Comment by mkoo** [comment]
That works too, or popup with hover action.
dealers choice!

**Comment by jdeck88** [comment]
ok, added some explanatory text there.... its in the code but not yet deployed...
