### ISSUE TITLE
Hillborn or Hilborn?

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#35]
I just noticed that we have :R. Hillborn 1969, v1334 in the title sections
and Hilborn, Ray in the author dropdown list.

Presumably the same guy!

**Comment by mkoo** [comment]
@jdeck88 FYI, Christina has fixed in the MODS so this just needs to be reingested to make live

**Comment by jdeck88** [comment]
i don't see an update to Git... Christina can you update the MODS file in
Git then i'll reingest.
thanks,
John

On Thu, Apr 7, 2016 at 8:24 AM, Michelle Koo notifications@github.com
wrote:

> @jdeck88 https://github.com/jdeck88 FYI, Christina has fixed in the
> MODS so this just needs to be reingested to make live
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BNHM/ecoreader/issues/35#issuecomment-206951693

## 

John Deck
(541) 914-4739

**Comment by jdeck88** [comment]
updated the data w/ latest mods files, fixed this.
John
