### ISSUE TITLE
Github webhooks failing

### ISSUE THREAD

**Issue by jdeck88** [BNHM/ecoreader#4]
It seems incoming files that should be some discoverable URL to an updated file is dropping the repo_url (not in payload??) and just being shown with the sha to start with:

51e966582f0859d597353d72d4bfd8036ac3fb90/docs/mvz/mods/httpweb.corral.tacc.utexas.eduMVZfieldnotesBensonSBv523-mod

it seems the repo_url is not being sent from github payload?

**Comment by cfidler** [comment]
I am working on another upload. Have you been abel to isolate what is happening? Do you want to touch base this morning?

**Comment by jdeck88** [comment]
Turning off web hooks... i think overall it is better to run the process manually when needed.  This lets us look at validation errors and time releases.
