### ISSUE TITLE
updates to *.jsp pages

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#41]
@jdeck88 Not sure what's the best workflow here... but I made updates to citation.jsp in the gh-pages branch (https://github.com/BNHM/ecoreader/blob/gh-pages/web/citation.jsp). This needs to be made live on the server, which perhaps should be done by you to avoid any confusion/conflicts. OK? Is that branch sync'ed to the live server?

**Comment by jdeck88** [comment]
I just made those changes in the master branch.  Also deployed.
