### ISSUE TITLE
alignment of search boxes on front page

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#42]
Fine to have the advanced search options up front all the time but need to line up those boxes!

Suggestion:
First line: Year boxes with the Scanned sections only box 

Skip a line.

Second line: Volume ID box

Skip a line 

Third line: Section Title with a longer box

Fourth line: Higher Geography boxes (when available #15 )

**Comment by jdeck88** [comment]
This now fixed and deployed... with most recent commit and now deployed.
