### ISSUE TITLE
remove content div on front page

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#43]
There are still some funny alignment issues on the front search page especially when you have no results. See below. Probably just removing the content div will fix (I hope)

![screenshot-ecoreader berkeley edu 2016-05-11 12-32-46](https://cloud.githubusercontent.com/assets/2523089/15194146/45fabeae-1776-11e6-8b5b-5b1414b80ea1.png)

**Comment by jdeck88** [comment]
fixed and deployed.

**Comment by mkoo** [comment]
Looks great.
