### ISSUE TITLE
v1748 not in Ecoreader

### ISSUE THREAD

**Issue by ccicero** [BNHM/ecoreader#48]
Dale McCullough was looking for v1748 which is a mixed-author volume. It's in Arctos under publications (something we need to deal with), and listed in the google doc of volume IDs, but that volume ID doesn't come up in Ecoreader (nor does the first author "Hines").

Field Notes: Cape Thompson Alaska 1959-1961, J.Q. Hines, D.W. Johnston, D.R. McCullough, M. Thompson, F.S.L. Williamson, E.J. Willoughby

**Comment by cfidler** [comment]
EcoReader is not complete. It mostly contains all the material that was in BSCIT. We should talk about how we are going to move forward with adding all of the missing volumes. I can get you that number by our next meeting.
