### ISSUE TITLE
Author list

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#5]
Would it be possible to adjust the author search to be a fuzzy search and have the list of authors be an optional search tool? This list of authors is long and is only going to get longer.

**Comment by jdeck88** [comment]
Start typing author names and have it start showing a drop-down list of author names that contain that search string?  or, begin with that search string?

**Comment by mkoo** [comment]
I like the former case!

On Friday, September 25, 2015, John Deck notifications@github.com wrote:

> Start typing author names and have it start showing a drop-down list of
> author names that contain that search string? or, begin with that search
> string?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BNHM/ecoreader/issues/5#issuecomment-143235898.

## 

Sent from Gmail Mobile

**Comment by cfidler** [comment]
I also vote for the former. Thanks, John!

**Comment by jdeck88** [comment]
This is now implemented. marking as resolved
