### ISSUE TITLE
odd results when searching for an author not listed

### ISSUE THREAD

**Issue by ccicero** [BNHM/ecoreader#50]
I just searched for author 'Kaiser' and when I hit submit, it returns a bunch of notes from misc. authors including Littlejohn, Alexander, Grinnell, etc. (none from Kaiser). If I do it again, same thing but a different set of misc. notes. Can we add a message or something when no results for an author are found?

**Comment by jdeck88** [comment]
this is fixed in latest commit.  Fix to show up on next deployment
