### ISSUE TITLE
EcoReader search is not working

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#52]
If I enter any name, I get an error. Error is "Error completing request!"

URL is http://ecoreader.berkeley.edu/?authors=Grinnell%2C%20Hilda%20W.&scanned_only=false

Thanks!
Christina

**Comment by jdeck88** [comment]
was in the middle of deploying the geographic search function....  Now it is live, so it solves this issue, plus the issue of adding geographic searches :)
