### ISSUE TITLE
Geography search

### ISSUE THREAD

**Issue by ccicero** [BNHM/ecoreader#53]
The new Geographic search function is great, thanks for implementing! Michelle said that it is parsing out the data from the section headings, is that correct? Shouldn't it only return those sections with that geography? e.g., I searched on "North America, Mexico, Baja California" and it returned a lot of notes that are not from Baja. See attached screen shot.

![image](https://cloud.githubusercontent.com/assets/967275/18099940/b67769a6-6e9d-11e6-9279-ba1046c7c17b.png)

**Comment by jdeck88** [comment]
I'm not sure this is a bug.  The geographic search looks at section geographies but results are always returned by the volume.    The volume itself _may_ contain references to other sections, e.g. in the index or perhaps other sections that may precede in time or space the returned result that could be of interest.  At any rate, if we do decide to return just sections as a result do we want to make this the default for all queries (e.g. for queries based on author name)? or, just queries based on geography?  what about queries based on both geography and author name?

**Comment by ccicero** [comment]
Christina explained where the data are coming from and that it's at the volume level. I think we at least need a little "i" icon with a pop-up window that explains that not all of the volumes have higher geography data populated yet, and that the query returns the entire volume even if just one section has that higher geography. Is that possible? Thanks.

**Comment by jdeck88** [comment]
So, an "i" icon placed after Geography like:
![unnamed](https://cloud.githubusercontent.com/assets/1154501/18135132/a8a06b76-6f55-11e6-88ef-bdf8944a58dd.jpg)

**Comment by jdeck88** [comment]
This issue covers #54 so will be closing that one.

**Comment by ccicero** [comment]
Yes, an "i" icon like in that image. Thanks.
