### ISSUE TITLE
link to page

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#60]
The "link to Image" function defaults to the first image of the volume. I just tried this for page 124 of volume 1426 and I couldn't get it. I can edit the URL to get the right image as an easy workaround.
Thanks!

**Comment by jdeck88** [comment]
What browser/OS are you using... I just tried it with Chrome on a mac and it links to the proper image.

**Comment by mkoo** [comment]
Same with Download this page link-- only first page of section 
This is what I downloaded even though I was looking at page 6 !
Happened on: Browser Chrome v62.0.3202.94/ PC
Same deal on FF v57/ PC

![image](https://user-images.githubusercontent.com/2523089/33344525-1ffc7072-d43e-11e7-9e12-a037cefb5dea.png)

PS. Should download this file (v1318_s2_p006.png):
![v1318_s2_p006](https://user-images.githubusercontent.com/2523089/33344885-488198d2-d43f-11e7-97ce-ee2360bdc185.png)

**Comment by jdeck88** [comment]
Note that this issue only appeared after browsing images, opening a large image, closing it and then clicking link to image or download.  In any case, the issue should now be fixed.
