### ISSUE TITLE
URL link doesn't work when there are geographies in the query

### ISSUE THREAD

**Issue by jdeck88** [BNHM/ecoreader#63]
users can copy the URL and save a query, but it doesn't work when geographies are part of the query

**Comment by jdeck88** [comment]
Implemented a fix so a single geography will work as part of saved URL.   Saving the results of Multiple selected geographies however, still do not work. this is a pretty complex procedure given the way the query URLs are both constructed and read.  Closing the issue for now... if there is a strong need for saving the results of multiple geographies i can re-open....

**Comment by mkoo** [comment]
I think that you'll have to make sure to include this functionality in any future dev on how ecoreader add geography to metadata as we discussed with IMLS-NLGM grant. But thanks for addressing in current system.
