### ISSUE TITLE
allow advanced searches on all authors

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#7]
Seems that author dropdown field is required for all searches. We should allow searches on all authors. EX. All field notes from 1940. All field notes sections from Alameda Co.

which brings up:
- search on only one year-- do you really have to put in 1940 - 1940 as the range to simply search on 1940?
- search on higher geography -- basically the info we have in section headers.

**Comment by mkoo** [comment]
BUmping up-- searching is limited to all authors right now and need to address these limits.

**Comment by jdeck88** [comment]
A few issues bundled here.  I fixed the main issue referenced in the title.  I need to remove the "onchange" author search functionality which got confusing if you are enabling searches without any authors.  At any rate, you can now leave author blank and do a search other items.

Searching on higher geography is already another issue, so can close it here.

I added an issue to track the date issue separately.

Closing this issue now.
