### ISSUE TITLE
Read Section option

### ISSUE THREAD

**Issue by mkoo** [BNHM/ecoreader#8]

**Comment by mkoo** [comment]
bumping this to a needed feature now....

**Comment by jdeck88** [comment]
Changed title of issue.

We decided in meeting today w/ Michelle, Christina, and Carla to have two links for sections:
[view section] -> current behaviour and resolution (can still click on individual images and zoom in) 
[read section] -> open the BIG pages and read through whole section (using previous/next functions)

a future option will be [download whole section] but that is another issue.

**Comment by jdeck88** [comment]
Fix committed to code today... deployed just now.
closing issue
